server:
  port: 8081

spring:
  application:
    name: onboarding-service
  datasource:
    url: jdbc:h2:mem:onboardingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  cloud:
    discovery:
      enabled: true

jwt:
  secret: my-secret-key-that-should-be-long-and-secure
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true        # ✅ Usa la IP en vez del hostname
    hostname: localhost            # ✅ Opcional: fuerza el uso de localhost como nombre

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
