server:
  port: 8081

spring:
  application:
    name: onboarding-service
  datasource:
    url: jdbc:h2:mem:onboardingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    deserialization:
      fail-on-unknown-properties: true

jwt:
  secret: my-secret-key-that-should-be-long-and-secure
  expiration: 3600000 # 1 hora en milisegundos

logging:
  level:
    org.springframework.security: DEBUG

